# Copyright 2016, Perceivon Hosting Inc.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY PERCEIVON HOSTING INC. AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL PERCEIVON HOSTING INC. OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
# ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
---
- name: Install some packages
  pkgng: name={{ item.name }} state=present
  with_items:
  - { name: secadm-kmod }
  - { name: secadm }
  tags:
  - secadm
  - pkg-server
- name: Check if secadm is already loaded
  shell:  kldstat -q -m secadm
  register: module_secadm_loaded
  ignore_errors: yes
  tags:
  - secadm
  - pkg-server
#- name: debug pf_nat_loaded
#  debug: var=pf_nat_loaded
#  tags:
#   - pf

- name: Load secadm
  shell: kldload secadm
  when:
  - module_secadm_loaded|failed
  - host_os == 'HardenedBSD'
  tags:
  - secadm
  - pkg-server

# FIXME: This is an incomprehensibly bad idea.
- name: Make secadm opt-in
  sysctl: name={{ item.name}} value={{ item.value }} state=present sysctl_set=yes
  when:
  - module_secadm_loaded|failed
  ignore_errors: true
  with_items:
  - { name: 'hardening.pax.mprotect.status', value: 1 }
  - { name: 'hardening.pax.aslr.status', value: 1 }
  - { name: 'hardening.pax.pageexec.status', value: 1 }
  tags:
  - secadm
  - pkg-server
