# Copyright 2015, Perceivon Hosting Inc.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY PERCEIVON HOSTING INC. AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL PERCEIVON HOSTING INC. OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
# ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
---
dependencies:
- role: nginx_proxy

- name: Make sure Jenkins jail is started
  iocage: state=started tag='{{ production_jails.jenkins.tag }}'
  register: jenkins_jail

- name: Enable jenkins services
  when:
  - jenkins_jail|success
  lineinfile: dest={{ jenkins_jail_dir.stat.path }}/etc/rc.conf state=present insertafter=EOF line="{{ item.line }}"
  with_items:
  - { line: "jenkins_enable=\"YES\"" }
  - { line: "jenkins_args=\"--webroot=/usr/local/jenkins/war --httpPort=8180 --prefix=/\"" }

- name: Install jenkins pkgs
  when:
  - jenkins_jail | success
  iocage: state=pkg tag={{ production_jails.jenkins.tag }} cmd="install -y {{ production_jails.jenkins.pkgs | join(' ') }}"
  register: jenkins_install

- name: Deploy Jenkins secadm config
  template: src='{{ item.name }}.j2' dest='{{ jenkins_jail_dir.stat.path }}/{{ item.path }}/{{ item.name }}' mode=0644 owner=818 group=818
  with_items:
  - { name: "secadm.rules", path: "/usr/local/etc", mode: 644 }
  when:
  - host_os == 'HardenedBSD'

- name: Load secadm rules
  iocage: state=exec tag={{ jenkins_jail.uuid }} cmd="/bin/sh -c \"secadm load /usr/local/etc/secadm.rules\""
  when:
  - jenkins_jail | success
  - host_os == 'HardenedBSD'

- name: Restart Jenkins
  iocage: state=exec tag={{ jenkins_jail.uuid }} cmd="/bin/sh -c \"service jenkins restart\""
  when:
  - jenkins_jail | success

- name: Create directories
  file: path={{ item.path }} state=directory mode={{ item.mode }} owner={{ item.owner }} group={{ item.group }}
  when:
  - jenkins_jail|success
  with_items:
  - { path: '{{ jenkins_jail_dir.stat.path }}/usr/local/jenkins/', mode: '755', owner: 818, group: 818 }

- name: Preload Jenkins
  shell: sleep 60 && fetch -o - http://{{ production_jails.jenkins.ip }}:8180/ >/dev/null
  ignore_errors: yes

- name: Find LDAP keyed password cookie
  stat: path={{ jenkins_jail_dir.stat.path }}/usr/local/jenkins/.pw.salted
  register: jenkins_pw_salted_cookie

- name: Obtain LDAP keyed password
  shell:  curl -d 'script=import hudson.util.Secret;def secret = Secret.fromString("{{ config.openldap.manager_password }}");println(secret.getEncryptedValue())' http://{{ production_jails.jenkins.ip }}:8180/scriptText/
  when: not jenkins_pw_salted_cookie.stat.exists
  register: jenkins_ldap_hash

- name: Deploy Jenkins configs Pt. I
  template: src='{{ item.name }}.j2' dest='{{ jenkins_jail_dir.stat.path }}/{{ item.path }}/{{ item.name }}' mode=0644 owner=818 group=818
  with_items:
  - { name: "config.xml", path: "/usr/local/jenkins", mode: 644 }
  - { name: "jenkins.model.JenkinsLocationConfiguration.xml", path: "/usr/local/jenkins", mode: 644 }
  - { name: "hudson.tasks.Mailer.xml", path: "/usr/local/jenkins", mode: 644 }
  when: not jenkins_pw_salted_cookie.stat.exists
  register: jenkins_configs

- name: Touch Jenkins .pw.salted file
  file: path="{{ jenkins_jail_dir.stat.path }}/usr/local/jenkins/.pw.salted" mode=644 owner=root group=wheel state=touch
  when: not jenkins_pw_salted_cookie.stat.exists
