# Copyright 2015, Perceivon Hosting Inc.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY PERCEIVON HOSTING INC. AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL PERCEIVON HOSTING INC. OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
# ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
---
- name: Check if zabbix jail already exists
  iocage: state=exists tag='{{ production_jails.zabbix.tag }}'
  ignore_errors: true
  register: zabbix_jail
  tags:
  - iocage-jails
  - zabbix
  - monitoring

- name: Create zabbix jail {{ production_jails.zabbix.tag }}
  iocage: state=cloned clone_from='{{ testing_jails.template.tag }}' tag={{ production_jails.zabbix.tag }} properties="ip4_addr='{{ production_jails.zabbix.interface }}|{{ production_jails.zabbix.ip }}' boot=on allow_sysvipc=1 defaultrouter='{{ internal_ip }}' resolver='nameserver {{ internal_ip }}' host_hostname='{{ production_jails.zabbix.tag }}'"
  when:
  - zabbix_jail|failed
  tags:
  - iocage-jails

- name: Register jail's root diretory
  stat: path='{{ iocage_mountpoint.stdout_lines[0] }}/tags/{{ production_jails.zabbix.tag }}/root/'
  register: zabbix_jail_dir
  tags:
  - iocage-jails

- assert:
    that:
      - zabbix_jail_dir is defined
      - zabbix_jail_dir.stat.exists
      - zabbix_jail_dir.stat.isdir
  tags:
  - iocage-jails
